### ISSUE TITLE
Slack notifications when a PR is opened

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/reactjs-boilerplate#86]

**Comment by G-N555** [comment]
It seems need to add github app on slack work channel.(probably need approval from security?)

- how to integrate slack and github(Japanese)
https://slack.com/intl/ja-jp/help/articles/232289568-GitHub-%E3%81%A8-Slack-%E3%82%92%E9%80%A3%E6%90%BA%E3%81%95%E3%81%9B%E3%82%8B

**Comment by G-N555** [comment]
Update:
I could integrated github on slack.

## Install `GitHub app` on Slack
1. go to slack
2. Go to `Apps` on the bottom of channel list on left panel
3. click `+` button(Or add apps)
4. search `github`
5. ckick `GitHub`(Not GitHub Actions)
6. You will see `Connect GitHub account` in the github apps on slack
7. click `Connect GitHub account`
8. move on app integration page, click `Connect GitHub account` button
9. click `continue`
10. note verification code, back to slack github app
11. type verification code after clicking `Enter code`, just below `Connect GitHub` account button
12. Your slack will connect your github account

## Install Slack app on Github
1. command any github config action e.g. `/github subscribe monstar-lab-oss/reactjs-boilerplate reviews` on slack
2. Github app asked you to install GitHub App on slack, click `Install GitHub App`
3. Go to the link, you'll see `monstar-lab-oss`(slack app is already installed, you can configure), click `configure`
4. Find repo `reactjs-boilerplate` after clicking `Select repositories` below `Only select repositories`
5. Click `Update access`

## Subscribe review notification
1. Command `/github subscribe monstar-lab-oss/reactjs-boilerplate review`

**Comment by G-N555** [comment]
## Documents
- [Github slack integration docs](https://github.com/integrations/slack#readme)

**Comment by jinmayamashita** [comment]
Awesome! It looks like I could be notified on the slack channel when a PR is opened (other than renovate PR), what do you think? 🤔
@mvn-binhnguyen-hn @mvn-dongho-dn @mvn-luanvu-hn @yannde FYI @G-N555

**Comment by mvn-luanvu-hn** [comment]
@jinmayamashita 
It's great! I'm OK with that.

**Comment by mvn-dongho-dn** [comment]
@jinmayamashita  
Yeah, I agree with that.

**Comment by ptrkdan** [comment]
It seems like this issue has been resolved already, so I'm closing it as resolved.
